name = "FiniteHorizonPOMDPs"
uuid = "8a13bbfe-798e-11e9-2f1c-eba9ee5ef093"
authors = ["Tomas Omasta <omastto1@fel.cvut.cz> and contributors"]
version = "0.2.0"

[deps]
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
NamedTupleTools = "0.13"
POMDPLinter = "0.1"
POMDPModelTools = "0.3"
POMDPs = "0.9"
julia = "1.5"

[extras]
DiscreteValueIteration = "4b033969-44f6-5439-a48b-c11fa3648068"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPTesting = "92e6a534-49c2-5324-9027-86e3c861ab81"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DiscreteValueIteration", "POMDPModels", "POMDPPolicies", "POMDPSimulators", "POMDPTesting"]
